#!/bin/bash
./run_triangle
./run_triangle
./run_triangle
./run_triangle
./run_triangle
./run_triangle
./run_triangle
./run_triangle
./run_triangle
./run_triangle
./run_triangle
./run_triangle
./run_triangle
./run_triangle
./run_triangle
./run_triangle
./run_triangle
./run_triangle
./run_triangle
./run_triangle
./run_triangle
./run_triangle
./run_triangle
./run_triangle